### ISSUE TITLE
フロントエンドにSoraのsignaling urlとchannel idを渡す

### ISSUE THREAD

**Issue by YHhaoareyou** [pf-hubs/chutvrc-reticulum#1]
### Sora契約開始まで

しばらくSora Laboを使っているため、signaling urlとchannel idは一旦Sora Laboの固定なものをハードコードで設定し、フロントエンドからのリクエストが来たらそのまま渡す

DL: 1/17

### Sora契約開始後

- フロントエンドに渡すを、別途生成したchannel idをとsignaling url（サーバーのホストとポート）に変える

**Comment by ikenichiro** [comment]
Close issue since the progress is considered done
